### ISSUE TITLE
Missing file extensions (?)

### ISSUE THREAD

**Issue by hasaezs** [Sama34/OUGC-Show-Avatar#2]
I have not tried anything , but apparently missing file extensions where the hooks or do not load ? At line [64](https://github.com/Sama34/OUGC-Show-Avatar/blob/master/Upload/inc/plugins/ougc_showavatar.php#L64).

**Comment by Sama34** [comment]
Nice catch. d9fe6596c054c435da23516835fe960f5ae6fa4e
